apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.serviceName }}
  labels:
    service: {{ .Values.kibana.name }}
spec:
  type: {{ .Values.kibana.service.spec.type }}
  selector:
    app: {{ .Values.kibana.name }}
  ports:
    - port: {{ .Values.kibana.container.containerPort.port }}
      targetPort: {{ .Values.kibana.container.containerPort.port }}