apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: {{ .Values.ingress.pizza_express.host }}
      http:
        paths:
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: {{ .Values.ingress.pizza_express.backend.service.name }}
                port:
                  number: {{ .Values.ingress.pizza_express.backend.service.port }}
    - host: {{ .Values.ingress.kibana.host }}
      http:
        paths:
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: {{ .Values.ingress.kibana.backend.service.name }}
                port:
                  number: {{ .Values.ingress.kibana.backend.service.port }}
